package vu.lt.mybatis.model;

public class Trainingprogram {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRAININGPROGRAM.COACH_ID
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    private Integer coachId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRAININGPROGRAM.PERSON_ID
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRAININGPROGRAM.NAME
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRAININGPROGRAM.COACH_ID
     *
     * @return the value of PUBLIC.TRAININGPROGRAM.COACH_ID
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    public Integer getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRAININGPROGRAM.COACH_ID
     *
     * @param coachId the value for PUBLIC.TRAININGPROGRAM.COACH_ID
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    public void setCoachId(Integer coachId) {
        this.coachId = coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRAININGPROGRAM.PERSON_ID
     *
     * @return the value of PUBLIC.TRAININGPROGRAM.PERSON_ID
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRAININGPROGRAM.PERSON_ID
     *
     * @param personId the value for PUBLIC.TRAININGPROGRAM.PERSON_ID
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRAININGPROGRAM.NAME
     *
     * @return the value of PUBLIC.TRAININGPROGRAM.NAME
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRAININGPROGRAM.NAME
     *
     * @param name the value for PUBLIC.TRAININGPROGRAM.NAME
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}