package vu.lt.mybatis.dao;

import vu.lt.mybatis.model.Coach;

import java.util.List;

public interface CoachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COACH
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COACH
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    int insert(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COACH
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    Coach selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COACH
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    List<Coach> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COACH
     *
     * @mbg.generated Tue May 19 18:20:00 EEST 2020
     */
    int updateByPrimaryKey(Coach record);
}